### PR TITLE
Do not process menu item selections when no PDF is loaded

### PR DESCRIPTION
**Pull request by Tommy-Geenexus**
Theres no need to process any item selections except for opening a document on initial app launch.
(Also deals with: "Uncaught ReferenceError: onRenderPage is not defined")

### CODE REVIEW

**Comment by thestinger** [comment]
`mUri` is set before the page is actually loaded, so this will need to be toggled via a callback: https://developer.android.com/reference/android/webkit/WebViewClient.html#onPageFinished(android.webkit.WebView, java.lang.String). I think it's probably before to disable and dim all of the non-functional actions at the start rather than producing errors, and then enable them when the page is ready. It will need to disable them again when triggering another load too.

**Comment by Tommy-Geenexus** [comment]
Thats what i thought of first, thought i dropped it because it would be harder to maintain.
But its the proper non half-baked way, so i'll go ahead and implement this hopefully soon.

**Comment by Tommy-Geenexus** [comment]
@thestinger 
Pr updated:
- All Items except "open document" are dimmed at first
- After page has finished loading, all will get enabled
- When reload with new document is triggered, items will be disabled and enabled after page has been loaded

**Comment by thestinger** [comment]
Thanks!

**Pull request merged**
