### PR TITLE
make Pdf Viewer behave like Android 5.0 "Document Task"

### PR DESCRIPTION
**Pull request by eighthave**
Android 5.0 started making document viewer apps behave like multiple windows.  This makes Pdf Viewer act like that.  It also makes Pdf Viewer listen to changes in the `ContentProvider` that it received files from other apps.  So if OpenKeychain locks, then Pdf Viewer will stop showing the PGP-encrypted document.

### CODE REVIEW

**Comment by eighthave** [comment]
added one fix to make sure the keyboard is hidden when launch, since OpenKeychain left it open when it prompts the user while decrypting.

**Comment by thestinger** [comment]
I applied one of the small fixes but I haven't had time to look at the rest and unfortunately this conflicts with some other small fixes that I merged.

**Comment by thestinger** [comment]
GitHub is doing something weird with the change log too.

**Comment by thestinger** [comment]
Updated to track oreo-mr1-release.

**Pull request closed without merging**
