### PR TITLE
Enable immersive mode for viewing PDF's

### PR DESCRIPTION
**Pull request by Tommy-Geenexus**
@thestinger 
This is now complete (at least from my POV), should be good to go.
I started building a version of aosp myself, with this app included, and i decided i will remove AppCompat references from #20, the disadvantages outweight the advantages by far.

I changed my mind, i think it'd be better now to take care of this pr first.

### CODE REVIEW

**Comment by Tommy-Geenexus** [comment]
@thestinger was this deliberately closed? Or should i rebase on another branch?

**Comment by thestinger** [comment]
No it wasn't deliberately closed. I think it just needs to be changed to oreo-r3-release, no rebase required. I'm having trouble keeping track of everything right now.

**Comment by thestinger** [comment]
Same with the other one. Google replaced oreo-r6-release with oreo-r1-release/oreo-r3-release (Pixel, Pixel XL), oreo-r4-release (Nexus 5X), oreo-r5-release (Nexus 6P).

The one that should be used as the target for pull requests is oreo-r3-release, the others are auto-generated.

**Comment by Tommy-Geenexus** [comment]
Thanks for the reply, acknowledged.

**Comment by thestinger** [comment]
Updated to track oreo-mr1-release.

**Comment by Tommy-Geenexus** [comment]
@thestinger 
This is now good to go, again. I've slimmed it down as much as i could.
Best way to go would be to merge #31, then i will rebase this one final time and it can be merged.

**Pull request closed without merging**
