### PR TITLE
Add support for encrypted PDF's

### PR DESCRIPTION
**Pull request by Tommy-Geenexus**
(Closes https://github.com/CopperheadOS/platform_packages_apps_PdfViewer/issues/15)
This adds support for reading password protected PDF's.
This is an initial approach, might need some rework / cleanup.

### CODE REVIEW

**Comment by Tommy-Geenexus** [comment]
Possible improvements:
- Error toast when entered password is invalid (?)

**Comment by Tommy-Geenexus** [comment]
@thestinger 

This patch is ready for review.

**Comment by Tommy-Geenexus** [comment]
@thestinger 
Updated to resolve merge conflicts.

**Comment by thestinger** [comment]
Is there a reason to use AppCompat? I'd prefer avoiding that.

**Comment by Tommy-Geenexus** [comment]
It's not necessary, but certain features like floating text on the password dialog would be vanished,
i.e. AppCompat allows access to some modern unique UI elements.
Not using it is going to reduce UX, and would prevent adding UI elements like
f.e. floating action button, etc....

**Comment by thestinger** [comment]
@Tommy-Geenexus Can you cherry-pick this to a new branch based on the new nougat-mr2-release branch and resubmit it as a pull request? I had to make a change to the history and I thought I'd be able to fix this for you but it won't allow that.

**Comment by Tommy-Geenexus** [comment]
@thestinger Done that.

**Comment by thestinger** [comment]
@Tommy-Geenexus Can you do https://github.com/CopperheadOS/platform_packages_apps_PdfViewer/pull/18 too? That's the one I'll likely want to merge first.

**Comment by Tommy-Geenexus** [comment]
@thestinger 
#18 needs some more inspection. 
I found something i might want to change, but haven't had time yet.
Taking care of #20 first would be a better approach in my opinion.

**Pull request closed without merging**
